version: 0.2

phases:
    build:
        commands:
            - echo Build started on `date`
            - mvn install
    post_build:
        commands:
            - echo Build completed on `date`
artifacts:
    files:
            - target/javawebdemo.war
            - appspec.yml
            - scripts/**/*
    discard-paths: no